name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🤗
  - type: checkboxes
    id: generic-bug-report-checklist
    attributes:
      label: Prerequisites
      description: "Before you continue make sure you have done all of the following:"
      options:
        - label: I have searched the [issues](https://github.com/ThatXliner/unmarkd/issues) and believe that it has not already been reported
          required: true
        - label: I have made sure this bug reproduces on the latest version
          required: true
        - label: "I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)"
          required: true
  - type: textarea
    id: bug-info
    attributes:
      label: Bug description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! What did you think should've happened?
      value: "A bug happened! There shouldn't be!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: What are the steps that you took to create this bug?
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: Other additional information that may deem useful. If you're sending code, please make an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)
      placeholder: "Environment, OS, debug logs, etc."
    validations:
      required: false
  - type: input
    id: repro-how-often
    attributes:
      label: Reproduces how often
      description: What percentage of the time does it reproduce?
      placeholder: "100% of the time? 75% of the times? Only when I do X?"
      value: "I can reproduce this bug 100% of the time"
    validations:
      required: true
