name: ✨ Feature request
description: Request a new feature, or a change in an existing one.
title: "[REQUEST]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: generic-feature-request-checklist
    attributes:
      label: Prerequisites
      description: "Before you start, make sure you have done all of the following:"
      options:
        - label: I have searched the [issues](https://github.com/ThatXliner/unmarkd/issues) and believe that it has not already been requested (and possibly rejected)
          required: true
        - label: I have made sure that this feature isn't possible with this project's plugin system and/or configuration and core changes must be made to make this happen
          required: true
        - label: "I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)"
          required: true
  - type: textarea
    id: feature-info
    attributes:
      label: Feature description
      description: Describe the feature
      placeholder: Tell us what you want to happen, and why can't it happen with our project's current customization (if you want to request enhancements to the plugin system/configuration/customization system, please file a seperate feature request for that)
      value: "Example: I want X which does Y, and this is a core change/I can't do right now because of Z"
    validations:
      required: true
