name: Release Asset Uploader
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build artifacts
        run: poetry build
      - name: Upload artifacts
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*

